# Generated by Django 6.0.3 on 2026-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(choices=[('completed', 'مكتملة'), ('returned', 'مرتجعة بالكامل')], db_index=True, default='completed', max_length=20),
        ),
    ]
