# Generated by Django 6.0.3 on 2026-05-31 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('merchants', '0002_merchant_invoice_note_merchant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب'), ('transport', 'نقل'), ('utilities', 'خدمات'), ('marketing', 'تسويق'), ('maintenance', 'صيانة'), ('purchase_related', 'مصاريف شراء'), ('other', 'أخرى')], default='other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expense_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='currencies.currency')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['merchant', 'expense_date'], name='expenses_ex_merchan_f1305a_idx'), models.Index(fields=['merchant', 'category'], name='expenses_ex_merchan_b10901_idx')],
            },
        ),
    ]
